In [35]:
import qutip 
from qutip import *
import numpy as np
import matplotlib.pyplot as plt
# Might be worth trying to download packages such as Scipy but we will see later on!

x = np.array([1,2,3,4,5])
r = np.random.randn(4,4)
print(Qobj(x))
print(Qobj(r))
#The dimensions, shape and input data can all be easily changed depending on what we want to do.

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]
Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[-0.0941815  -0.42190444 -0.78295741 -1.24592116]
 [-1.02699308 -1.46889962  1.18761614 -0.18760889]
 [-0.42842774 -1.14286727  0.17580371 -1.85984916]
 [ 1.52049587  2.18927375 -0.2963006   0.72182152]]


In [26]:
n=fock(4,1) # Provides basis vectors in Fock Space
destroy(3) # Lowering operator 
coherent(5,2).dag() #find hermitian conjugate 
coherent(5,2).tr() # finds trace of matrix / vector

#Clearly we can create quantum objects in different basis states. We also have the ability 
# to easily manipulate them using inbuilt operators!



0.14864196494651485

In [38]:
vac = fock(5,0) # vaccum state vector within hilbert with number states [0,1,2,3,4]
a = destroy(5) # This is the annhilation operator for 5 number states
a*vac # we find what we would expect of the annhilation operator acting on the ground state!

# Lets see what happens when we apply this to a different number state

num= fock(5,3)
a*num # This returns us a lowered basis vector multiped by sqrt(3)

c = create(5) # creation operator for 5 number states ranging from 0 -> 4 

# Again lets see what happens when we apply this to the vaccum state and the 3rd number state!
print(c*vac)
print(c*num)

#We get exactly what we expect, number state raised by one step and multiplied by a constant
#It's also possible to use them multiple times e.g

print(c**3 * vac) # Clearly has been raised 3 times and multipled by sqrt(6) ( sqrt(2 * 3) )
# This is going to be SUPER useful for when we want to investigate the quantum self sustained oscillators 
#Their master equations are powers of these creation and annihilation operators, nice to see how user friendly it is 
#to interact with these things.

# We can produce superpositions of state 
ket =( fock(5,0) + fock(5,3)).unit()
print(ket)


Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]]
Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [2.]]
Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.        ]
 [0.        ]
 [0.        ]
 [2.44948974]
 [0.        ]]


In [51]:
# In our project we're interested in non-equilliberium dynamics and so the master equation using density operators is important
# we can construct density operators.

ket = fock(5,2) 
print(ket*ket.dag())
# ket2dm takes a bra or ket and transforms it into a density matrix.
# This is the inbuilt function way to do what we saw above |n><n|
print(ket2dm(ket))


Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [34]:
#Expectation value
vac = fock(5,0)
one = fock(5,1)
two = fock(5,2)
x =( vac + one + two).unit()
x2 = 0.5*ket2dm(vac) + 0.3*ket2dm(one) + 0.2*(ket2dm(two))

c = create(5)
n = num(5)
np.testing.assert_almost_equal(expect(n,vac),0) # Raises an error if the two are not equal to a desired amount.
np.testing.assert_almost_equal(expect(n,one),1)
#As the code runs smoothly we can see that the expectation value of an operator in a given state is what we want
#i.e <N>|1 = 1

(ket2dm(vac)**2).tr()
(ket2dm(x)**2).tr()
n_th_a

1.0000000000000007

In [ ]:
#Harmonic Oscillator for 10 number states
x = 10

